#!/bin/bash

set -eu

if [[ -f ./user-setting ]] ; then
  source ./user-setting
fi

: ${USERNAME:?USERNAME is not given.}
: ${PASSWORD:?PASSWORD is not given.}
: ${RECEIVERS:?RECEIVERS is not given.}

: ${SMTP_URL:=smtp.gmail.com}
: ${SMTP_PORT:=587}

: ${SENDER_EMAIL:=consul-alerts@gmail.com}

: ${CONSUL_ALERTS_HOME:=$(cd $(dirname $0) && pwd)}
: ${CONSUL_ALERTS_LOG_DIR:=${CONSUL_ALERTS_HOME}/log}
CONSUL_NOTIFICATION_LOG=${CONSUL_ALERTS_LOG_DIR}/consul-notification.log

CONSUL_ALERTS_EMAIL_CONFIG_API=http://localhost:8500/v1/kv/consul-alerts/config/notifiers/email
CONSUL_ALERTS_CHECK_CONFIG_API=http://localhost:8500/v1/kv/consul-alerts/config/checks
CONSUL_ALERTS_LOG_CONFIG_API=http://localhost:8500/v1/kv/consul-alerts/config/notifiers/log

curl -X PUT -d "true"            ${CONSUL_ALERTS_EMAIL_CONFIG_API}/enabled
curl -X PUT -d "${USERNAME}"     ${CONSUL_ALERTS_EMAIL_CONFIG_API}/username
curl -X PUT -d "${PASSWORD}"     ${CONSUL_ALERTS_EMAIL_CONFIG_API}/password
curl -X PUT -d "${RECEIVERS}"    ${CONSUL_ALERTS_EMAIL_CONFIG_API}/receivers
curl -X PUT -d "${SMTP_URL}"     ${CONSUL_ALERTS_EMAIL_CONFIG_API}/url
curl -X PUT -d "${SMTP_PORT}"    ${CONSUL_ALERTS_EMAIL_CONFIG_API}/port
curl -X PUT -d "${SENDER_EMAIL}" ${CONSUL_ALERTS_EMAIL_CONFIG_API}/sernder-email

curl -X PUT -d 30 ${CONSUL_ALERTS_CHECK_CONFIG_API}/change-threshold

curl -X PUT -d "${CONSUL_NOTIFICATION_LOG}" ${CONSUL_ALERTS_LOG_CONFIG_API}/path
