#!/bin/bash

BASE_DIR=$(cd $(dirname $0) && pwd)

: ${CONSUL_ALERTS_HOME:=${BASE_DIR}}
: ${CONSUL_ALERTS_BIN:=${BASE_DIR}/bin/consul-alerts}
: ${CONSUL_ALERTS_LOG_DIR:=${CONSUL_ALERTS_HOME}/log}

: ${CONSUL_BIN_DIR:=${BASE_DIR}/../consul-study/bin}

export PATH=${PATH}:${CONSUL_BIN_DIR}

mkdir -p ${CONSUL_ALERTS_LOG_DIR}

export 

${CONSUL_ALERTS_BIN} start --watch-events --watch-checks \
	2>&1 | tee ${CONSUL_ALERTS_LOG_DIR}/out.log
