#!/bin/bash

BASE_DIR=$(cd $(dirname $0) && pwd)

: ${CONSUL_BIN_DIR:=${BASE_DIR}/../consul-study/bin}
: ${CONSUL_ALERTS_HOME:=${BASE_DIR}}
: ${CONSUL_ALERTS_BIN:=${CONSUL_ALERTS_HOME}/bin/consul-alerts}
: ${CONSUL_ALERTS_LOG_DIR:=${CONSUL_ALERTS_HOME}/log}

: ${CONSUL_ALERTS_BIN_DIR:=${BASE_DIR}/bin}

export PATH=${PATH}:${CONSUL_ALERTS_BIN_DIR}:${CONSUL_BIN_DIR}

mkdir -p ${CONSUL_ALERTS_LOG_DIR}

${CONSUL_ALERTS_BIN} start --watch-events --watch-checks 2>&1 | tee ${CONSUL_ALERTS_LOG_DIR}/out.log
